### ISSUE TITLE
partsLeft does not update correctly?

### ISSUE THREAD

**Issue by Fonta1n3** [bitcoinppl/bbqr-swift#1]
When running `continuousJoiner` it always prints `added item, 1 parts left` regardless of how many parts are actually left.

It would be nice to be able to display to the user % completion.

**Comment by praveenperera** [comment]
@Fonta1n3 hey when i run the demo thats not what I see, I see

```
added item, 6 parts left
added item, 5 parts left
added item, 4 parts left
added item, 3 parts left
added item, 2 parts left
added item, 1 parts left
```

Can you post your code?

**Comment by Fonta1n3** [comment]
Ah I see I need to split the original string into an array first then pass to split.

**Comment by praveenperera** [comment]
Yes the idea of the `ContinousJoiner` is that you would pass it into it one by one as you scan each QR code.

Is there any doc changes you could suggest? @Fonta1n3

**Comment by Fonta1n3** [comment]
My bad, the QR I was scanning was only two parts...

**Comment by praveenperera** [comment]
@Fonta1n3 no worries, just wondering if i could do something to make the docs clearer

**Comment by praveenperera** [comment]
@Fonta1n3 i added an example of using `Joined` directly, which lets you join all the parts together without having to do it one by one

https://github.com/bitcoinppl/bbqr-ffi/commit/cb97f5de6cecddfcbdaa1af6347b39d51ba66f21
